services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "ecommerce"
    ports:
      - "3306:3306"
    volumes:
      - ecommerce-mysql-data:/var/lib/mysql

volumes:
  ecommerce-mysql-data:
